"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
const API="https://api.mail.gw", LIFETIME=10*60*1000;
type Session={accountId:string;address:string;password:string;token:string;expiresAt:number};
type Summary={id:string;subject?:string;intro?:string;createdAt?:string;from?:{address?:string;name?:string}};
type Detail=Summary&{html?:string[];text?:string;attachments?:{id:string;filename?:string}[]};
async function request(path:string,options:RequestInit={},token?:string){const response=await fetch(`${API}${path}`,{...options,headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail["hydra:description"]||detail.message||`Mail service returned ${response.status}`)}return response}
function cleanEmailHtml(source:string){const doc=new DOMParser().parseFromString(source,"text/html");doc.querySelectorAll("script,style,link,iframe,frame,object,embed,form,input,button,textarea,select,meta,base").forEach(n=>n.remove());doc.querySelectorAll("*").forEach(node=>{for(const attr of [...node.attributes]){const name=attr.name.toLowerCase(),value=attr.value.trim();if(name.startsWith("on")||name==="srcset"||name==="style")node.removeAttribute(attr.name);if((name==="href"||name==="src")&&!/^(https?:|mailto:|data:image\/)/i.test(value))node.removeAttribute(attr.name);if(name==="src"&&/^https?:/i.test(value))node.removeAttribute("src")}if(node.tagName==="A"){node.setAttribute("target","_blank");node.setAttribute("rel","noopener noreferrer")}});return `<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline';"><style>body{font:15px/1.55 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;color:#172033;margin:20px;overflow-wrap:anywhere}a{color:#d95739}img{max-width:100%;height:auto}</style>${doc.body.innerHTML}`}
const time=(ms:number)=>{const s=Math.max(0,Math.ceil(ms/1000));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};
export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[messages,setMessages]=useState<Summary[]>([]),[selected,setSelected]=useState<Detail|null>(null),[remaining,setRemaining]=useState(LIFETIME),[customName,setCustomName]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("Ready when you are.");const destroying=useRef(false);
 const destroy=useCallback(async(reason="Inbox destroyed. Nothing remains in this browser.")=>{if(destroying.current)return;destroying.current=true;const current=session;sessionStorage.removeItem("tempmail-session");setSession(null);setMessages([]);setSelected(null);setNotice(reason);setRemaining(LIFETIME);if(current)await request(`/accounts/${current.accountId}`,{method:"DELETE"},current.token).catch(()=>null);destroying.current=false},[session]);
 const refresh=useCallback(async(quiet=false)=>{if(!session)return;if(!quiet)setNotice("Checking for mail…");try{const data=await(await request("/messages?page=1",{},session.token)).json();setMessages(data["hydra:member"]||data.member||[]);if(!quiet)setNotice("Inbox is up to date.")}catch(error){setNotice(error instanceof Error?error.message:"Could not refresh inbox.")}},[session]);
 async function createInbox(){setBusy(true);setNotice("Creating your private session…");try{const domains=await(await request("/domains?page=1")).json();const domain=(domains["hydra:member"]||domains.member||[]).find((x:{isActive?:boolean})=>x.isActive!==false)?.domain;if(!domain)throw new Error("No temporary-mail domain is available right now.");const base=customName.trim()||`quick-${crypto.getRandomValues(new Uint32Array(2)).join("").slice(0,12)}`;if(!/^[a-zA-Z0-9._-]{1,40}$/.test(base))throw new Error("Use only letters, numbers, dots, underscores, or hyphens.");const address=`${base}@${domain}`,password=`${crypto.randomUUID()}-${crypto.randomUUID()}`;const account=await(await request("/accounts",{method:"POST",body:JSON.stringify({address,password})})).json();const tokenData=await(await request("/token",{method:"POST",body:JSON.stringify({address,password})})).json();const next={accountId:account.id,address,password,token:tokenData.token,expiresAt:Date.now()+LIFETIME};sessionStorage.setItem("tempmail-session",JSON.stringify(next));setSession(next);setNotice("Inbox ready. It will self-destruct in 10 minutes.")}catch(error){setNotice(error instanceof Error?error.message:"Could not create an inbox.")}finally{setBusy(false)}}
 async function openMessage(m:Summary){if(!session)return;setNotice("Opening message…");try{setSelected(await(await request(`/messages/${m.id}`,{},session.token)).json());setNotice("Message opened safely. Remote images are blocked.")}catch(error){setNotice(error instanceof Error?error.message:"Could not open message.")}}
 async function downloadAttachment(a:{id:string;filename?:string}){if(!session||!selected)return;try{const response=await request(`/messages/${selected.id}/attachment/${a.id}`,{},session.token),url=URL.createObjectURL(await response.blob()),anchor=document.createElement("a");anchor.href=url;anchor.download=a.filename||"attachment";anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{setNotice("That attachment could not be downloaded.")}}
 useEffect(()=>{const saved=sessionStorage.getItem("tempmail-session");if(!saved)return;try{const parsed=JSON.parse(saved)as Session;if(parsed.expiresAt>Date.now())setSession(parsed);else sessionStorage.removeItem("tempmail-session")}catch{sessionStorage.removeItem("tempmail-session")}},[]);
 useEffect(()=>{if(!session)return;refresh(true);const timer=setInterval(()=>{const left=session.expiresAt-Date.now();setRemaining(left);if(left<=0)destroy("Time’s up. The disposable inbox was destroyed.")},1000),poller=setInterval(()=>refresh(true),12000);return()=>{clearInterval(timer);clearInterval(poller)}},[session,refresh,destroy]);
 const iframeHtml=useMemo(()=>selected?.html?.[0]?cleanEmailHtml(selected.html[0]):null,[selected]);
 return <main className="shell"><header className="topbar"><div className="brand"><span className="mark">tm</span><div><strong>tempMail</strong><small>one inbox · ten minutes</small></div></div><span className="privacy">Browser-local session</span></header>{!session?<section className="launch card"><div className="eyebrow">Disposable by design</div><h1>An inbox for the next ten minutes.</h1><p>Receive the one email you need, then destroy the address. No account, no shared inbox list, and no credentials stored on this website.</p><label>Optional username<input value={customName} onChange={e=>setCustomName(e.target.value)} placeholder="leave blank for random" maxLength={40}/></label><button className="primary" onClick={createInbox} disabled={busy}>{busy?"Creating…":"Create disposable inbox"}</button><div className="safety"><span>Public app</span><p>Anyone can use this webpage, but every browser gets a different inbox. Don’t use temporary email for medical, financial, identity, or password-recovery messages.</p></div></section>:<section className="workspace"><aside className="mailbox card"><div className="timer"><span>Self-destructs in</span><strong>{time(remaining)}</strong></div><div className="address"><code>{session.address}</code><button onClick={()=>navigator.clipboard.writeText(session.address)}>Copy</button></div><div className="actions"><button onClick={()=>refresh(false)}>Refresh</button><button className="danger" onClick={()=>destroy()}>Destroy now</button></div><div className="listHead"><strong>Messages</strong><span>{messages.length}</span></div><div className="messageList">{messages.length===0?<div className="empty"><b>Waiting for mail</b><span>We check every 12 seconds.</span></div>:messages.map(m=><button className={`message ${selected?.id===m.id?"active":""}`} key={m.id} onClick={()=>openMessage(m)}><b>{m.from?.name||m.from?.address||"Unknown sender"}</b><strong>{m.subject||"(no subject)"}</strong><span>{m.intro||"Open message"}</span></button>)}</div></aside><article className="reader card">{!selected?<div className="readerEmpty"><div className="envelope">✉</div><h2>Your message will appear here</h2><p>Leave this tab open while you wait.</p></div>:<><div className="messageHead"><button className="back" onClick={()=>setSelected(null)}>← Back</button><h2>{selected.subject||"(no subject)"}</h2><p>From {selected.from?.name||selected.from?.address}</p></div>{selected.attachments?.length?<div className="attachments">{selected.attachments.map(a=><button key={a.id} onClick={()=>downloadAttachment(a)}>↓ {a.filename||"Attachment"}</button>)}</div>:null}{iframeHtml?<iframe title="Email content" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={iframeHtml}/>:<pre>{selected.text||selected.intro||"This message has no readable body."}</pre>}</>}</article></section>}<footer><span>{notice}</span><a href="https://mail.gw/" target="_blank" rel="noreferrer">Powered by Mail.gw</a></footer></main>}
